upload images and svg index.html
KaterynaBabiak/2_Binabox pull request #5
Opened 2024-08-02 09:54 UTC by KaterynaBabiak

2024-08-06 20:55 UTC, per-aspera-ad-astra commented on about-us.html
> +                    <img src="./img/ralph-edwards-founder.webp" alt="" class="team-img">
Previous solution with text in `alt` attribute was better

2024-08-07 16:23 UTC, per-aspera-ad-astra commented
Great job in general!
Some points to improvement:
- Some images have an empty alt attribute - better add text here.
- Name of image files - there are file names starting with a capital letter(for example Minus.svg), some starting with a lowercase letter, and there are spaces in the names (Icon Search.svg). There should be one approach to naming files - all words with a lowercase letter are separated by a hyphen (like most of your files).
- Please check the icons you load from the svg-sprite - I didn’t see any of them on my side. For example social media list:
<img width="372" alt="Screenshot 2024-08-07 at 19 22 02" src="https://github.com/user-attachments/assets/abf063fd-0de4-46a6-925d-0dc7662971b3">

2024-08-08 08:10 UTC, KaterynaBabiak commented
I've checked the way of adding svg from sprite and I  don't understand why you couldn't see all of them.  Could you check one more time, please?  And if it doesn't work could you explain me what i have to do to fix these issues? Because everything looks good on my screen.

![team-section](https://github.com/user-attachments/assets/dea80a7e-5588-474b-bc79-5d11e8e7aa86)
![join-us](https://github.com/user-attachments/assets/e6f8c706-3085-4faa-aeff-799418460cf1)

2024-08-08 10:37 UTC, per-aspera-ad-astra commented
Sorry for the inconvenience, you are right - the sprite icons works, it's my mistake.

There are one thing to improve that I missed the first time - I can't see `width` and `height `attributes on `img` tags - need to add them.

2024-08-08 11:12 UTC, KaterynaBabiak commented
Thanks for comments, I've added some missing width & height property for img tags in styles.css.

2024-08-08 12:50 UTC, per-aspera-ad-astra commented
> Thanks for comments, I've added some missing width & height property for img tags in styles.css.

I mean add width and height as html-attributes, not like css properties :)

2024-08-08 13:25 UTC, KaterynaBabiak commented
Is it wrong way to add width and height as css properties?
I mean if we have a lot of images in one group with the same size, do we need to write same width and height next to each image?  
I will fixed all as you've recomended me but I just want to understand which way is better and why.

2024-08-09 08:07 UTC, per-aspera-ad-astra commented
In the task description it is written:
"Add basic sizes: width and height, in tags." - I was guided by this point.

In real projects, a group of images with the same size is usually output using a loop, meaning you will need to specify the dimensions of the image once.

Your solution is not wrong - css is also used for define sizes.

You can read for example this article - [https://habr.com/ru/articles/524918/](https://habr.com/ru/articles/524918/)

2024-08-09 09:51 UTC, KaterynaBabiak commented
Thanks for the explanation and the article was very useful for me.
I've changed the image sizes as it was written in the task description.

2024-08-09 15:19 UTC, per-aspera-ad-astra approved these changes

2024-08-09 15:20 UTC, per-aspera-ad-astra commented
Approved.
Can be merged into main branch.

2024-08-14 13:39 UTC, per-aspera-ad-astra commented on css/styles.css
> +    color: #FFFFFF;
You can reduce` #FFFFFF` to `#fff`

2024-08-14 16:20 UTC, per-aspera-ad-astra commented on css/styles.css
> +    line-height: 22px;
I would advise setting the `line-height` in dimensionless quantities - here it's 1.57 (22px / 14px). Would be good if you will do it whole project

2024-08-14 16:28 UTC, per-aspera-ad-astra commented on contact-us.html
> +                <form action="#" method="get" class="contact-us-form">
`method` should be `post`

2024-08-14 16:32 UTC, per-aspera-ad-astra commented
If we start typing inside input it height will change
<img width="463" alt="Screenshot 2024-08-14 at 19 30 25" src="https://github.com/user-attachments/assets/2de8ad2d-c7b6-4348-bcd7-e583d14c079a">

2024-08-14 16:36 UTC, per-aspera-ad-astra commented on contact-us.html
>                          type="text"
All elements inside form (except button) should have labels according to acceptance criteria

2024-08-14 16:39 UTC, per-aspera-ad-astra commented
If search field not in focus the text becomes black:
<img width="249" alt="Screenshot 2024-08-14 at 19 38 39" src="https://github.com/user-attachments/assets/0433555c-d04e-4c60-8061-1b06cf4f06c9">

2024-08-14 19:53 UTC, per-aspera-ad-astra commented on css/styles.css
> +    background-size: cover;
better  use `background-size: contain `in this case - `cover` can crop the image

2024-08-14 19:56 UTC, per-aspera-ad-astra commented on css/styles.css
> +    background: url(../img/icons/minus-.svg);
use `background-image` instead -  shorthand property `background` reset your `background-size`

2024-08-14 20:01 UTC, per-aspera-ad-astra commented on css/styles.css
> +.sidebar-item {
Please add `cursor: pointer` for this selector - user should be able to see that is clickable element

2024-08-14 20:13 UTC, per-aspera-ad-astra commented on css/styles.css
> +*.sidebar-label .sidebar-checkbox:checked ~ .checkmark:after {
try not to use universal selector (*)

2024-08-14 20:17 UTC, per-aspera-ad-astra requested changes
Good work!

What I liked:

- Work meets general requirements - all forms implemented, they have validation, buttons have type attributes, forms have validation

What need to improve:

- Most information provided in comments. additionaly - I see a lot of places where you use `font-weight: 400;`, I'm  sure you can remove most of them because this is default value

2024-08-15 19:06 UTC, per-aspera-ad-astra approved these changes
Can be merged into main branch

2024-08-15 19:12 UTC, merged